apiVersion: apps/v1
kind: Deployment
metadata: 
  name: chat-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: chat-app
  template: 
    metadata: 
      labels: 
        app: chat-app
    spec: 
      automountServiceAccountToken: false
      containers: 
        - name: chat-app
          image: dinhtri69/chat-app:latest
          ports:
            - containerPort: 80
          resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi" # Đây là dòng giới hạn RAM tối đa để sửa lỗi SonarCloud
            cpu: "500m"
